#include <SFML\Graphics.hpp>


	const int HEIGHT_MAP = 30;//размер карты высота
	const int WIDTH_MAP = 30;// размер карты ширина

	sf::String TileMap[HEIGHT_MAP] = {
		"llllllllllllllllllllllllllllll",
		"llllllllllllllllllllllllllllll",
		"llooooooooooooooooooooooooooll",
		"llooooooooooooooooooooooooooll",
		"llookkookkookkookkookkookkooll",
		"llookkookkookkookkookkookkooll",
		"llookkookkookkookkookkookkooll",
		"llookkookkookkookkookkookkooll",
		"llookkookkookkmmkkookkookkooll",
		"llookkookkookkmmkkookkookkooll",
		"llookkookkookkookkookkookkooll",
		"llookkookkooooooooookkookkooll",
		"llookkookkooooooooookkookkooll",
		"llooooooooookkookkooooooooooll",
		"llooooooooookkookkooooooooooll",
		"llkkookkkkooooooooookkkkookkll",
		"llmmookkkkooooooooookkkkoommll",
		"llooooooooookkookkooooooooooll",
		"llooooooooookkkkkkooooooooooll",
		"llookkookkookkkkkkookkookkooll",
		"llookkookkookkookkookkookkooll",
		"llookkookkookkookkookkookkooll",
		"llookkookkookkookkookkookkooll",
		"llookkookkooooooooookkookkooll",
		"llookkookkooooooooookkookkooll",
		"llookkookkoookkkkoookkookkooll",
		"lloooooooooookghkoooooooooooll",
		"lloooooooooookbnkoooooooooooll",
		"llllllllllllllllllllllllllllll",
		"llllllllllllllllllllllllllllll",
	};
	void qwe(int i) {
		if (i == 1) {
			TileMap[2] = { "llooooooooooooooooooooooooooll", };
			TileMap[3] = { "llooooooooooooooooooooooooooll" };
			TileMap[4] = { "llookkookkookkookkookkookkooll", };
			TileMap[5] = { "llookkookkookkookkookkookkooll", };
			TileMap[6] = { "llookkookkookkookkookkookkooll", };
			TileMap[7] = { "llookkookkookkookkookkookkooll", };
			TileMap[8] = { "llookkookkookkmmkkookkookkooll", };
			TileMap[9] = { "llookkookkookkmmkkookkookkooll", };
			TileMap[10] = { "llookkookkookkookkookkookkooll", };
			TileMap[11] = { "llookkookkooooooooookkookkooll", };
			TileMap[12] = { "llookkookkooooooooookkookkooll", };
			TileMap[13] = { "llooooooooookkookkooooooooooll", };
			TileMap[14] = { "llooooooooookkookkooooooooooll", };
			TileMap[15] = { "llkkookkkkooooooooookkkkookkll", };
			TileMap[16] = { "llmmookkkkooooooooookkkkoommll", };
			TileMap[17] = { "llooooooooookkookkooooooooooll", };
			TileMap[18] = { "llooooooooookkkkkkooooooooooll", };
			TileMap[19] = { "llookkookkookkkkkkookkookkooll", };
			TileMap[20] = { "llookkookkookkookkookkookkooll", };
			TileMap[21] = { "llookkookkookkookkookkookkooll", };
			TileMap[22] = { "llookkookkookkookkookkookkooll", };
			TileMap[23] = { "llookkookkooooooooookkookkooll", };
			TileMap[24] = { "llookkookkooooooooookkookkooll", };
			TileMap[25] = { "llookkookkoookkkkoookkookkooll", };
			TileMap[26] = { "lloooooooooookghkoooooooooooll", };
			TileMap[27] = { "lloooooooooookbnkoooooooooooll", };
		}
		if (i == 2) {
			TileMap[2] = { "lloooooommoooooommooooooooooll" };
			TileMap[3] = { "lloooooommoooooommooooooooooll" };
			TileMap[4] = { "llookkoommooooookkookkookkooll" };
			TileMap[5] = { "llookkoommooooookkookkookkooll" };
			TileMap[6] = { "llookkooooooookkkkookkmmkkooll" };
			TileMap[7] = { "llookkooooooookkkkookkmmkkooll" };
			TileMap[8] = { "llooooookkoooooooooommooooooll" };
			TileMap[9] = { "llooooookkoooooooooommooooooll" };
			TileMap[10] = { "lluuooookkoooommooookkuukkmmll" };
			TileMap[11] = { "lluuooookkoooommooookkuukkmmll" };
			TileMap[12] = { "lluuuuooooookkoooommoouuooooll" };
			TileMap[13] = { "lluuuuooooookkoooommoouuooooll" };
			TileMap[14] = { "llookkkkkkuuuuuummoooouukkooll" };
			TileMap[15] = { "llookkkkkkuuuuuummoooouukkooll" };
			TileMap[16] = { "lloooooommuukkookkookkookkooll" };
			TileMap[17] = { "lloooooommuukkookkookkookkooll" };
			TileMap[18] = { "llmmkkoommookkookkooooookkooll" };
			TileMap[19] = { "llmmkkoommookkookkooooookkooll" };
			TileMap[20] = { "llookkookkookkkkkkookkmmkkooll" };
			TileMap[21] = { "llookkookkookkkkkkookkmmkkooll" };
			TileMap[22] = { "llookkoouuookkkkkkooooooooooll" };
			TileMap[23] = { "llookkoouuookkkkkkooooooooooll" };
			TileMap[24] = { "llookkooooooooooooookkookkooll" };
			TileMap[25] = { "llookkoooooookkkkoookkookkooll" };
			TileMap[26] = { "llookkookkoookghkoookkkkkkooll" };
			TileMap[27] = { "llookkookkoookbnkoookkkkkkooll" };
		}
		if (i == 3) {
			TileMap[2] = { "llooooooookkooooookkooooooooll" };
			TileMap[3] = { "llooooooookkooooookkooooooooll" };
			TileMap[4] = { "lloouuuuuuokooooooooooooooooll" };
			TileMap[5] = { "lloouuuuuuokoooooooooommmmmmll" };
			TileMap[6] = { "lloouuuuuuooooooooooooooooooll" };
			TileMap[7] = { "llkkuuuuuuooooooooooooooooooll" };
			TileMap[8] = { "lluuuuuuuuooooookkookkkkkkkoll" };
			TileMap[9] = { "lluuuuuuuuooooookkookkkkkkkoll" };
			TileMap[10] = { "lluuuuuuuukkkkkkkkookkoookooll" };
			TileMap[11] = { "lluuuuuuuukkkkkkooookkoookooll" };
			TileMap[12] = { "lluuuuuuuuooookkoooooooookooll" };
			TileMap[13] = { "lluuuuuuuuooookkoooooooookooll" };
			TileMap[14] = { "lloouuoooooooommmmmmoooouuooll" };
			TileMap[15] = { "lloouuoooooooommmmmmoooouuooll" };
			TileMap[16] = { "lloooooooooooooooooouuuuuuuull" };
			TileMap[17] = { "llookkookkoooooooooouuuuuuuull" };
			TileMap[18] = { "llkkkookkkoookkkkkkkuuuuuuuull" };
			TileMap[19] = { "llkkkookkkoookoooooouuuuuuuull" };
			TileMap[20] = { "llooooooooookkoooooouuuuuuuull" };
			TileMap[21] = { "llooooooooookkookkkkuuuuuuuull" };
			TileMap[22] = { "llkkoooomoooooookkkkuuuuuuooll" };
			TileMap[23] = { "llkkoooomooooooooooouuuuuuooll" };
			TileMap[24] = { "llkkkkoomooooooooooouuuuuuooll" };
			TileMap[25] = { "llkkkkoomooookkkkooouuuuuuooll" };
			TileMap[26] = { "llmmkkkkoooookghkoookkooooooll" };
			TileMap[27] = { "llmmkkkkoooookbnkoookkooooooll" };
		}
		if (i == 4) {
			TileMap[2] = { "lloouuuuoooooooooooooooouuooll" };
			TileMap[3] = { "lloouuuuoooooooooooooooouuooll" };
			TileMap[4] = { "lluuuuooooookkkkoooooooooouull" };
			TileMap[5] = { "lluuuuooookkkkkkkkkkoooooouull" };
			TileMap[6] = { "lluuoooookkkkkkkkkkkkkoooommll" };
			TileMap[7] = { "lluuoooookkkkkkkkkkkkkkkooooll" };
			TileMap[8] = { "llmmooookkkkkkkkkkkkkkkkkoooll" };
			TileMap[9] = { "llooooookkkkkkkkkkkkkkkkkoooll" };
			TileMap[10] = { "lloooookkkooooookkkkkkookoooll" };
			TileMap[11] = { "lloooookooooooooookkkkookoooll" };
			TileMap[12] = { "llvvoookoomooomoookkkoooooooll" };
			TileMap[13] = { "llvvoookoomooomoookkkoooooooll" };
			TileMap[14] = { "llooookkooooooooookkkooovvvvll" };
			TileMap[15] = { "llooookkookkkkooookkkooovvvvll" };
			TileMap[16] = { "llooookkkkkkkkkkkkkkkkooooooll" };
			TileMap[17] = { "llooookkkkkkkkkkkkkkkkooooooll" };
			TileMap[18] = { "lloookkkkkkkkkkkkkkkkkkoooooll" };
			TileMap[19] = { "lloookkkkkkkkkkkkkkkkkkoooooll" };
			TileMap[20] = { "llookkkkkkkkkkkkkkkkkkkkooooll" };
			TileMap[21] = { "llooooookkkkkkkkkkkkooooooooll" };
			TileMap[22] = { "llookkkkookkkkkkkkookkkkoouull" };
			TileMap[23] = { "llookkkkkkookkkkookkkkkkoouull" };
			TileMap[24] = { "lluuookkkkooooooookkkkoouuuull" };
			TileMap[25] = { "lluuoooooooookkkkooooooouuuull" };
			TileMap[26] = { "llmmuuoooooookghkooooouuuummll" };
			TileMap[27] = { "llmmuuoooooookbnkooooouuuummll" };
		}
		if (i == 5) {
			TileMap[2] = { "llooooooookkkkooooooooooooooll" };
			TileMap[3] = { "llooooooookkkkooooooooooooooll" };
			TileMap[4] = { "llooooooookkoooooommmmmmooooll" };
			TileMap[5] = { "llmmookkookkoooooooooommooooll" };
			TileMap[6] = { "llmmookkooooookkooooooooooooll" };
			TileMap[7] = { "llmmookkooooookkooooooooooooll" };
			TileMap[8] = { "llkkookkkkkkookkkkoovvvvoovvll" };
			TileMap[9] = { "llkkookkkkkkookkkkoovvvvoovvll" };
			TileMap[10] = { "llkkooooookkoooooooovvooooooll" };
			TileMap[11] = { "llkkooooookkoooooooovvooooooll" };
			TileMap[12] = { "lloooooooovvvvoovvvvvvookkkkll" };
			TileMap[13] = { "llooookkoovvvvoovvvvvvookkkkll" };
			TileMap[14] = { "llkkkkoooovvkkookkkoooooooooll" };
			TileMap[15] = { "llkkkkoooovvkkookkkoooooooooll" };
			TileMap[16] = { "lloooooooovvooooooooooommoooll" };
			TileMap[17] = { "lloooooooovvooooooooooommoooll" };
			TileMap[18] = { "llvvvvvvoovvoommookkooomooooll" };
			TileMap[19] = { "llvvvvvvoovvoommookkooomooooll" };
			TileMap[20] = { "llooooooooooooooooooooomkkkkll" };
			TileMap[21] = { "llooooookkkkooooooooooomkkkkll" };
			TileMap[22] = { "llooooooookkkkkkkkkkooooooooll" };
			TileMap[23] = { "llooooooookkooooookkkkooooooll" };
			TileMap[24] = { "llkkkkkkooooooooooookkkkooooll" };
			TileMap[25] = { "llkkkkoooooookkkkoooookkooooll" };
			TileMap[26] = { "llkkoooooooookghkoooooooooooll" };
			TileMap[27] = { "lloooooooooookbnkoooooooooooll" };
		}
		if (i == 6) {
			TileMap[2] = { "lloooooooooookookouuuuooooooll" };
			TileMap[3] = { "lloooooooooookookouuuuooooooll" };
			TileMap[4] = { "llookoomookooooooookuukookuull" };
			TileMap[5] = { "llookoomookooooooookuukookuull" };
			TileMap[6] = { "llookoomookoookkoookuukookuull" };
			TileMap[7] = { "llookoomookoookkoookuukookuull" };
			TileMap[8] = { "llookkooookkoommookkuuookkuull" };
			TileMap[9] = { "llookkooookkoommookkuuookkuull" };
			TileMap[10] = { "lloooooookmmookkookkmooouuuull" };
			TileMap[11] = { "lloooooookooookkoooomooouuuull" };
			TileMap[12] = { "llkkkkkooooouukkuuoooookkkkkll" };
			TileMap[13] = { "llkkkkkooooouukkuuoooookkkkkll" };
			TileMap[14] = { "lloooooooookuuuuuukoooooooooll" };
			TileMap[15] = { "lloooooooookuuuuuukoooooooooll" };
			TileMap[16] = { "llmmkkkkookkuuuuuukkokkkkkmmll" };
			TileMap[17] = { "llmmkkkkoooouuuuuuoookkkkkmmll" };
			TileMap[18] = { "llmmmmmmoooooouuoooooommmmmmll" };
			TileMap[19] = { "llooooooookkoouuookkooooooooll" };
			TileMap[20] = { "llookkooookkooooookkooooooooll" };
			TileMap[21] = { "llookkooookkooooookkooooooooll" };
			TileMap[22] = { "llookkkoooookkookkoooookkkuull" };
			TileMap[23] = { "llookkkooooooooooooooookkkuull" };
			TileMap[24] = { "llooookkoooooooooooooouuuuuull" };
			TileMap[25] = { "lloooooooooookkkkooooouuuuuull" };
			TileMap[26] = { "lloooooooooookghkooooooouuuull" };
			TileMap[27] = { "lloooooooooookbnkooooooouuuull" };
		}
		if (i == 7) {
			TileMap[2] = { "lloooooooooooooommmmooooooooll" };
			TileMap[3] = { "llooooooooooooooooooooooooooll" };
			TileMap[4] = { "lloooommmmmmmmoooooooommooooll" };
			TileMap[5] = { "lloooommoooooooooooooommooooll" };
			TileMap[6] = { "lloooommoooooooooooooommooooll" };
			TileMap[7] = { "lloooommoooooouuoommmmmmooooll" };
			TileMap[8] = { "lloommoooooouummoooooommooooll" };
			TileMap[9] = { "lloommoooooouummoooooommooooll" };
			TileMap[10] = { "lloooooooouummmmoooooommmmooll" };
			TileMap[11] = { "lloooooooouummmmoooooommmmooll" };
			TileMap[12] = { "lloommoouummmmmmoommooooooooll" };
			TileMap[13] = { "lloommoouummmmmmoommooooooooll" };
			TileMap[14] = { "llooomoommmmoooooommmmooooooll" };
			TileMap[15] = { "llooomoommmmoooooommmmooooooll" };
			TileMap[16] = { "llmooooooommoommmmmmooooomooll" };
			TileMap[17] = { "llmooooooommoommmmmmooooomooll" };
			TileMap[18] = { "llooommmoooooommmmuuoooommooll" };
			TileMap[19] = { "llooommmoooooommmmuuoooommooll" };
			TileMap[20] = { "lloommoooooooommuuoooommmmooll" };
			TileMap[21] = { "lloommoooooooommuuoooommmmooll" };
			TileMap[22] = { "lloommmmmmoooouuoooommooooooll" };
			TileMap[23] = { "lloooooommoooouuoooommooooooll" };
			TileMap[24] = { "lloooooooooooooooooommoooommll" };
			TileMap[25] = { "lloooooooooookkkkooooooommmmll" };
			TileMap[26] = { "lloooooooooookghkoooooooooooll" };
			TileMap[27] = { "llmmmmoooooookbnkoooooooooooll" };
		}
		if (i == 8) {
			TileMap[2] = { "llooookkooookkooooookkooooooll" };
			TileMap[3] = { "llooookkooookkooooookkooooooll" };
			TileMap[4] = { "lluukkkkkkookkooooookkkoooooll" };
			TileMap[5] = { "lluukkkkkkookkoommookkkoooooll" };
			TileMap[6] = { "lluuuuuuooookkookkookkoookkoll" };
			TileMap[7] = { "lluuuuuuooooooookkoooooookkoll" };
			TileMap[8] = { "lluuvvvvvvvvvvvvvvvvvvvvoovvll" };
			TileMap[9] = { "lluuvvvvvvvvvvvvvvvvvvvvoovvll" };
			TileMap[10] = { "llookkooooooooooooooooooooooll" };
			TileMap[11] = { "llookkooooooooookkooooooooooll" };
			TileMap[12] = { "llooookkoooookkkkkkkkkkkmmmmll" };
			TileMap[13] = { "llooookkoooookkkkkookkooooooll" };
			TileMap[14] = { "llkkkkookkoookkkkkkkkkooookkll" };
			TileMap[15] = { "llkkkkookkoookkkkkkkkkmmmmkkll" };
			TileMap[16] = { "lloooooommoooooouuuuuuuuooooll" };
			TileMap[17] = { "lloooooommoommoouuuuuuuuooooll" };
			TileMap[18] = { "llvvvvoovvvvvvvvvvoovvvvvvvvll" };
			TileMap[19] = { "llvvvvoovvvvvvvvvvoovvvvvvvvll" };
			TileMap[20] = { "lluuuuoookooooooooooooooooooll" };
			TileMap[21] = { "lluuuuoookooookkkkooooooooooll" };
			TileMap[22] = { "lluuuukkookooooookooooookkooll" };
			TileMap[23] = { "lluuuukkookooooooooommkkkkooll" };
			TileMap[24] = { "lluuookkoookooooooookkookkooll" };
			TileMap[25] = { "lluummkkookookkkkoooooookkooll" };
			TileMap[26] = { "lloooooooooookghkoooooookkooll" };
			TileMap[27] = { "lloooooooooookbnkoookkooooooll" };
		}
		if (i == 9) {
			TileMap[2] = { "llooooooooooooooooooooooooooll" };
			TileMap[3] = { "lloooooooooooooooommooooooooll" };
			TileMap[4] = { "lloooooooooooouuommmmoooooooll" };
			TileMap[5] = { "lloooooooooommuuommmmoooooooll" };
			TileMap[6] = { "lloooooouoommmmooommooooooooll" };
			TileMap[7] = { "lloooommuoommmmoooooooooooooll" };
			TileMap[8] = { "llooommmmooommuuooooooooooooll" };
			TileMap[9] = { "llooommmmooooouuooooooooooooll" };
			TileMap[10] = { "lloooommuoooooooooooooooooooll" };
			TileMap[11] = { "llooooooooooooooooooooooooooll" };
			TileMap[12] = { "lloooouooooooouuoouoooooooooll" };
			TileMap[13] = { "lloooouommuuoouummuoooooooooll" };
			TileMap[14] = { "llooooommmmoooommmmooooooommll" };
			TileMap[15] = { "llooooommmmoooommmmooooooommll" };
			TileMap[16] = { "lloooouummuuoouummuuooooooooll" };
			TileMap[17] = { "lloooouuoouuoouuoouoooooooooll" };
			TileMap[18] = { "llooooooooooooooooooooooooooll" };
			TileMap[19] = { "lloooooommoooooommooooooooooll" };
			TileMap[20] = { "llooooommmmoooommmmoooooookkll" };
			TileMap[21] = { "llooooommmmoooommmmoooooookkll" };
			TileMap[22] = { "lloooouummuuoouummuoooooookkll" };
			TileMap[23] = { "lloooouuoouuoouuoouoooooookkll" };
			TileMap[24] = { "llooooooooooooooooooooooooooll" };
			TileMap[25] = { "llookkoooooookkkkoooooooooooll" };
			TileMap[26] = { "llookkkkoooookghkoookkooooooll" };
			TileMap[27] = { "llookkkkoooookbnkoookkkkooooll" };
		}
		if (i == 10) {
			TileMap[2] = { "llooooooooooooooooooooooooooll" };
			TileMap[3] = { "llooooooooooooooooooooooooooll" };
			TileMap[4] = { "lloookkkkkooooooooooookkkkkoll" };
			TileMap[5] = { "lloookookkooooooooooookkookoll" };
			TileMap[6] = { "llokkkooookkoouuuuookkoooookll" };
			TileMap[7] = { "llokooooookkoouuuuookkoooookll" };
			TileMap[8] = { "llkkooooookkuuuuuuuukkoooookll" };
			TileMap[9] = { "llkkooooookkuuuuuuuukkoooookll" };
			TileMap[10] = { "llkkoooookkkuummmmuukkkooookll" };
			TileMap[11] = { "llkkoooookkkuummmmuukkkooookll" };
			TileMap[12] = { "llokooookkvvvvvvvvvvvvkkkkkkll" };
			TileMap[13] = { "llokkkkkkkvvvvvvvvvvvvkkkkkkll" };
			TileMap[14] = { "llookkkkkkmmmmkkmmmmkkkkkkkoll" };
			TileMap[15] = { "llookkkkkkmmmmkkmmmmkkkkkkkoll" };
			TileMap[16] = { "llooookkkkmmookkoommkkkkkoooll" };
			TileMap[17] = { "llooookkkkmmookkoommkkkkkoooll" };
			TileMap[18] = { "llooookkkkkkkkkkkkkkkkkkkoooll" };
			TileMap[19] = { "llooookkkkkkkkkkkkkkkkkkkoooll" };
			TileMap[20] = { "llkkuukkkkkkmmmmkkkkkkkkuukkll" };
			TileMap[21] = { "llkkuuoooooommmmoooooooouukkll" };
			TileMap[22] = { "llkkuuuuuuuuuuuuuuuuuuuuuukkll" };
			TileMap[23] = { "llkkuuuuuuuuuuuuuuuuuuuuuukkll" };
			TileMap[24] = { "lloooouuuuuuoooooouuuuuuuuooll" };
			TileMap[25] = { "lloooouuuuuuokkkkouuuuuuuuooll" };
			TileMap[26] = { "llooooookooookghkoooookoooooll" };
			TileMap[27] = { "llooooookooookbnkoooookoooooll" };
		}
		if (i == 11) {
			TileMap[2] = { "lloooooooooommookkookkkkooooll" };
			TileMap[3] = { "lloooooooooommookkookkkkooooll" };
			TileMap[4] = { "lloookkkkkkkkkookkooooooooooll" };
			TileMap[5] = { "lloookkkkkkkkkookkooooooooooll" };
			TileMap[6] = { "llooooookoookkookkkkoouuuuuull" };
			TileMap[7] = { "llooooookoookkookkkkoouuuuuull" };
			TileMap[8] = { "lloookoooooooooommoouuuuuuuull" };
			TileMap[9] = { "lloookoooooooooommoouuuuuuuull" };
			TileMap[10] = { "lloookookkkkkkmmkkkkuuuukkmmll" };
			TileMap[11] = { "lloookookkkkkkmmkkkkuuuuoommll" };
			TileMap[12] = { "llookkkkkkmmooookkoouuuuoookll" };
			TileMap[13] = { "lloooooooommooookkoouuuuoookll" };
			TileMap[14] = { "llokkkkkkkoommuuuuuuuuuuooooll" };
			TileMap[15] = { "llokkkkkkkoommuuuuuuuuuuooooll" };
			TileMap[16] = { "lloooooommoooouuuuuuuuuukkooll" };
			TileMap[17] = { "lloooooommoooouuuuuuuuuukkooll" };
			TileMap[18] = { "llmmkkoouuuuuuuummuuuuuukkooll" };
			TileMap[19] = { "llmmkkoouuuuuuuummuuuuuukkooll" };
			TileMap[20] = { "llokkkuuuuuuuuuuooooooookkkoll" };
			TileMap[21] = { "llokkkuuuuuuuuuuooooooookkkoll" };
			TileMap[22] = { "llookkuuuuoooooooommkkkkkkooll" };
			TileMap[23] = { "llookkuuuuooooooooookkkkkkooll" };
			TileMap[24] = { "lloooouuuuooooooooookkoookooll" };
			TileMap[25] = { "lloooouuuuoookkkkoookkoookooll" };
			TileMap[26] = { "lloooouuuuoookghkoooooooooooll" };
			TileMap[27] = { "llookkuuuuoookbnkoooooooooooll" };
		}
		if (i == 12) {
			TileMap[2] = { "llooooooooooooookkkkooooooooll" };
			TileMap[3] = { "llooooooooooooookkkkooooooooll" };
			TileMap[4] = { "llookkkkkkoooooooooookooooooll" };
			TileMap[5] = { "llookkkkkkkkoooooooookooooooll" };
			TileMap[6] = { "llooooooookkooooooooooooookkll" };
			TileMap[7] = { "llooooooookkooooooooooooookkll" };
			TileMap[8] = { "lloovvvvvvvvvvookkkoooookkmmll" };
			TileMap[9] = { "lloovvvvvvvvvvookkkoooookkooll" };
			TileMap[10] = { "lloooooooooovvookkoommmokkooll" };
			TileMap[11] = { "lloooommmmmmvvookkoommmokkooll" };
			TileMap[12] = { "llooookkookkvvvvvvoovvkkkkooll" };
			TileMap[13] = { "llooookkookkvvvvvvoovvkkkkooll" };
			TileMap[14] = { "lloooooooommvvoooooovvmmooooll" };
			TileMap[15] = { "lloooooooommvvoooooovvooooooll" };
			TileMap[16] = { "llvvvvvvoovvvvkkkkoovvooooooll" };
			TileMap[17] = { "llvvvvvvoovvvvkkkkoovvooooooll" };
			TileMap[18] = { "llooooooooookkmmmmoovvvvvvooll" };
			TileMap[19] = { "llooooooooookkoooooovvvvvvooll" };
			TileMap[20] = { "llkkkkkkooooooooooooooooooooll" };
			TileMap[21] = { "llkkkkkkooooooooooooooooooooll" };
			TileMap[22] = { "llooookkoommmmooooookkkkoookll" };
			TileMap[23] = { "llooookkooooooooooookkkkoookll" };
			TileMap[24] = { "llkkooooooooooooooookkooookkll" };
			TileMap[25] = { "llkkoooooooookkkkoookkooookkll" };
			TileMap[26] = { "lloooooooooookghkoooooooooooll" };
			TileMap[27] = { "lloooooooooookbnkoooooooooooll" };
		}
		if (i == 13) {
			TileMap[2] = { "llooooooooooooooooooooooooooll" };
			TileMap[3] = { "llooooooookkooooookkooooooooll" };
			TileMap[4] = { "llookkkkkkkkooooookkkkkkkkooll" };
			TileMap[5] = { "llookkkkkkkkooooookkkkkkkkooll" };
			TileMap[6] = { "llookkooooooookkoooooooommooll" };
			TileMap[7] = { "llookkooooooookkoooooooommooll" };
			TileMap[8] = { "lloommookkkkooooookkkkookkkkll" };
			TileMap[9] = { "lloommokkoooooooooookkookkkkll" };
			TileMap[10] = { "llookkookouuoommoouuokoommkkll" };
			TileMap[11] = { "llookkookouummmmmmuuokoommkkll" };
			TileMap[12] = { "llookkoooouuuuuuuuuuoooommkkll" };
			TileMap[13] = { "lloooooooouuuuuuuuuuooooookkll" };
			TileMap[14] = { "lloooooooouuuuuuuuuuooooookkll" };
			TileMap[15] = { "llkkmmoooouuuuuuuuuuooookkkkll" };
			TileMap[16] = { "llkkmmookouummmmmmuuokookkooll" };
			TileMap[17] = { "llkkmmookouuoommoouuokookkooll" };
			TileMap[18] = { "llkkkkookkooooooooookkoommooll" };
			TileMap[19] = { "llkkkkookkkkooooookkkkoommooll" };
			TileMap[20] = { "llkkmmooooooookkooooooookkooll" };
			TileMap[21] = { "llkkmmooooooookkooooooookkooll" };
			TileMap[22] = { "llkkkkkkkkkkooooookkkkkkmmmmll" };
			TileMap[23] = { "llkkkkkkkkkkooooookkkkkkmmmmll" };
			TileMap[24] = { "llkkkkooookkooooookkooookkooll" };
			TileMap[25] = { "llkkkkoooooookkkkoooooookkooll" };
			TileMap[26] = { "llkkkkoooooookghkoooooooooooll" };
			TileMap[27] = { "llkkkkoooooookbnkoooooooooooll" };
		}
		if (i == 14) {
			TileMap[2] = { "llooooooooooooooooooooooooooll" };
			TileMap[3] = { "llooooooooooooooooooooooooooll" };
			TileMap[4] = { "lluuuuooooookkkkkkoooooouuuull" };
			TileMap[5] = { "lluuuuooookkkkkkkkkkoooouuuull" };
			TileMap[6] = { "lluuoooookkkkkkkkkkkkooooouull" };
			TileMap[7] = { "lluuoooookkkkkkkkkkkkooooouull" };
			TileMap[8] = { "llooooookkkkuukkuukkkkooooooll" };
			TileMap[9] = { "llooooookkkkuukkuukkkkooooooll" };
			TileMap[10] = { "llooooookkuuuukkuuuukkooooooll" };
			TileMap[11] = { "llooooookkuuuukkuuuukkooooooll" };
			TileMap[12] = { "lluuooookkkkkkkkkkkkkkoooouull" };
			TileMap[13] = { "lluuooookkkkkkkkkkkkkkoooouull" };
			TileMap[14] = { "lluuuuooookkuukkuukkoooouuuull" };
			TileMap[15] = { "lluuuuooookkuukkuukkoooouuuull" };
			TileMap[16] = { "llvvvvvvookkkkkkkkkkoovvvvvvll" };
			TileMap[17] = { "llvvvvvvookkkkkkkkkkoovvvvvvll" };
			TileMap[18] = { "lloooooooookokokokokooooooooll" };
			TileMap[19] = { "lloooooooookokokokokooooooooll" };
			TileMap[20] = { "llooooooookokokokokoooooooooll" };
			TileMap[21] = { "llooooooookokokokokoooooooooll" };
			TileMap[22] = { "llomomomoooooooooooooomomomoll" };
			TileMap[23] = { "llomomomoooooooooooooomomomoll" };
			TileMap[24] = { "llkokokooooooooooooooookokokll" };
			TileMap[25] = { "llkokokooooookkkkooooookokokll" };
			TileMap[26] = { "llmomomoomoookghkooomoomomomll" };
			TileMap[27] = { "llmomomoomoookbnkooomoomomomll" };


		}
		if (i == 15) {
			TileMap[2] = { "llooooooookkkkooookkooooooooll" };
			TileMap[3] = { "llooooooookkkkooookkooooooooll" };
			TileMap[4] = { "lloouuuukkkkooooookkooooooooll" };
			TileMap[5] = { "lloouuuukkkkooooookkooooooooll" };
			TileMap[6] = { "lluuuuuuuuuuuuuuuukkkkooooooll" };
			TileMap[7] = { "lluuuuuuuuuuuuuuuukkkkooooooll" };
			TileMap[8] = { "lluummkkuukkkkkkuuuuuuuukkmmll" };
			TileMap[9] = { "lluuookkuukkkkkkuuuuuuuukkmmll" };
			TileMap[10] = { "lluuuukkuuuuuummuuuukkmokkooll" };
			TileMap[11] = { "lluuuukkuuuuuuoouuuukkmokkooll" };
			TileMap[12] = { "lloouuuukkoouuuuuuuukkookkooll" };
			TileMap[13] = { "lloouuuukkmmuuuuuuuukkookkooll" };
			TileMap[14] = { "llookkkkkkkkkkuuuukkkkkouuuull" };
			TileMap[15] = { "llookkkkkkkkkkuuuukkkkkouuuull" };
			TileMap[16] = { "llommmkkkkooooookkkkoooooouull" };
			TileMap[17] = { "llomookkkkooooookkoooooooouull" };
			TileMap[18] = { "llookkookkooooookkuuuukkkouull" };
			TileMap[19] = { "llookkookkoommkkoouuuukkkouull" };
			TileMap[20] = { "llookkoooookkkkkuuuukkoooouull" };
			TileMap[21] = { "llookkoooookkkoouuuukkoooouull" };
			TileMap[22] = { "llookkkkkookkkuuuuoouukkuuuull" };
			TileMap[23] = { "llookkkkkookoouuuukkuukkuuuull" };
			TileMap[24] = { "llooookkoouuooooookkuukkuuooll" };
			TileMap[25] = { "llooookkoouuokkkkokkuuoouuooll" };
			TileMap[26] = { "llooookkoooookghkooouuuuuuooll" };
			TileMap[27] = { "lloooooooooookbnkooouuuuuuooll" };
		}
		if (i == 16) {
			TileMap[2] = { "llooooooooooooooooooooooooooll" };
			TileMap[3] = { "llooooooooooooooooooooooooooll" };
			TileMap[4] = { "lloooommuummooooooooooooooooll" };
			TileMap[5] = { "lloooommuummooooooooooooooooll" };
			TileMap[6] = { "lloooooouuoouuooooooooooooooll" };
			TileMap[7] = { "lloooooouuoouummooooooooooooll" };
			TileMap[8] = { "lloouuoooooooouuooooooooooooll" };
			TileMap[9] = { "lloouuoooooooouukkooooooooooll" };
			TileMap[10] = { "lloouuuuoooouuoouuooooooooooll" };
			TileMap[11] = { "lloouuuuoooouuoouummooooooooll" };
			TileMap[12] = { "lloouuoouuoouuoooouuooooooooll" };
			TileMap[13] = { "lloouuoouuoouuoooouukkooooooll" };
			TileMap[14] = { "lloouuoooouuoooooouuuuooooooll" };
			TileMap[15] = { "lloouuoooouuoooooouuuummooooll" };
			TileMap[16] = { "lloooouuoooooooouuuuuuuuooooll" };
			TileMap[17] = { "lloooouuoooooooouuuuuuuukkooll" };
			TileMap[18] = { "lloooooouuoooouuoouuuuuuuuooll" };
			TileMap[19] = { "lloooooouuoooouuoouuuuuuuuooll" };
			TileMap[20] = { "llkkoooooooooouuoooouuuuuummll" };
			TileMap[21] = { "llkkoooooooooouuoooouuuuuummll" };
			TileMap[22] = { "llkkkkoooooooooouuoouuuuuuuull" };
			TileMap[23] = { "llkkkkoooooooooouuoouuuuuuuull" };
			TileMap[24] = { "llmmkkkkoooooooooouuoouuuuuull" };
			TileMap[25] = { "llmmkkkkoooookkkkouuoouuuuuull" };
			TileMap[26] = { "llmmmmkkkkoookghkoookkoouuuull" };
			TileMap[27] = { "llmmmmkkkkoookbnkoookkoouuuull" };
		}
		if (i == 17){
			TileMap[2] = { "llooooooooooooooooooooooooooll" };
			TileMap[3] = { "llooooooookkooooooooookkooooll" };
			TileMap[4] = { "llookkookkkkoooojjjjjjkkkkooll" };
			TileMap[5] = { "llookkookkkkoooojjjjjjkkkkooll" };
			TileMap[6] = { "llookkooookkoommjjjjjjjjjjooll" };
			TileMap[7] = { "llookkooookkoommjjjjjjjjjjooll" };
			TileMap[8] = { "lljjjjjjmokkooookkjjjjjjjjooll" };
			TileMap[9] = { "lljjjjjjmokkooookkjjjjjjjjooll" };
			TileMap[10] = { "lljjjjjjjjjjjjkkkkokkoooooooll" };
			TileMap[11] = { "lljjjjjjjjjjjjkkkkokkoooooooll" };
			TileMap[12] = { "llooooomjjjjjjjjkkokkooommmmll" };
			TileMap[13] = { "llooooomjjjjjjjjkkokkoooooooll" };
			TileMap[14] = { "llkkkkkkkkjjjjjjjjjjjjjjkkkkll" };
			TileMap[15] = { "llkkkkkkkkjjjjjjjjjjjjjjkkkkll" };
			TileMap[16] = { "llooooookkkkjjjjjjjjmoooooooll" };
			TileMap[17] = { "llooooookkkkjjjjjjjjmoooooooll" };
			TileMap[18] = { "llookkkkkkoojjjjjjkkkkookkooll" };
			TileMap[19] = { "llookkkkkkoojjjjjjkkkkookkooll" };
			TileMap[20] = { "lljjjjjjkkjjooooooookkookkooll" };
			TileMap[21] = { "lljjjjjjkkjjooooooookkookkooll" };
			TileMap[22] = { "lljjjjjjjjjjmmoommooooookkooll" };
			TileMap[23] = { "lljjjjjjjjjjooooooooookkkkooll" };
			TileMap[24] = { "llkkjjjjjjjjooooooookkooooooll" };
			TileMap[25] = { "llkkjjjjjjjjokkkkoookkooooooll" };
			TileMap[26] = { "llkkkkmooooookghkoookkookkooll" };
			TileMap[27] = { "llkkkkmooooookbnkoookkookkooll" };
		}
		if (i == 18) {
			TileMap[2] = { "lloooooooooooooooommmmmmuuooll" };
			TileMap[3] = { "lloooooooooooooooommmmmmuuooll" };
			TileMap[4] = { "llookkoooooooooooommoooommooll" };
			TileMap[5] = { "llookkoooooooooooommoooommooll" };
			TileMap[6] = { "llkkuukkooooookkkkkkkkoommooll" };
			TileMap[7] = { "llkkuukkooooookkkkkkkkoommooll" };
			TileMap[8] = { "llookkuukkooookkoouukkmmmmooll" };
			TileMap[9] = { "llookkuukkooookkoouukkmmmmooll" };
			TileMap[10] = { "llooookkoouummkkuuookkooooooll" };
			TileMap[11] = { "llooookkoouummkkuuookkooooooll" };
			TileMap[12] = { "lloooooooommookkmmkkkkooooooll" };
			TileMap[13] = { "lloooooooommookkmmkkkkooooooll" };
			TileMap[14] = { "llooookkkkmmkkoommooooooooooll" };
			TileMap[15] = { "llooookkkkmmkkoommooooooooooll" };
			TileMap[16] = { "llooookkoouukkmmuuooooooooooll" };
			TileMap[17] = { "llooookkoouukkmmuuooooooooooll" };
			TileMap[18] = { "llmmmmmmuuookkooookkkkooooooll" };
			TileMap[19] = { "llmmmmmmuuookkooookkkkooooooll" };
			TileMap[20] = { "llmmookkkkkkkkooookkmmmmooooll" };
			TileMap[21] = { "llmmookkkkkkkkooookkmmmmooooll" };
			TileMap[22] = { "llmmoooommoooooooooommkkkkooll" };
			TileMap[23] = { "llmmoooommoooooooooommkkkkooll" };
			TileMap[24] = { "lluummmmmmooooooooooookkmmmmll" };
			TileMap[25] = { "lluummmmmmoookkkkoooookkmmmmll" };
			TileMap[26] = { "lloooooooooookghkooooooommmmll" };
			TileMap[27] = { "lloooooooooookbnkooooooommmmll" };
		}
		if (i == 19) {
			TileMap[2] = { "llookkookkookkookkookkookkooll" };
			TileMap[3] = { "llookkookkookkookkookkookkooll" };
			TileMap[4] = { "llookkookkookkookkookkookkooll" };
			TileMap[5] = { "llookkookkookkookkookkookkooll" };
			TileMap[6] = { "lloommoommoommoommoommoommooll" };
			TileMap[7] = { "llooooooooooooooooooooooooooll" };
			TileMap[8] = { "llooooooookkooooookkooooooooll" };
			TileMap[9] = { "llkkookkookkooooookkookkookkll" };
			TileMap[10] = { "llkkookkkkkkookkookkkkkkookkll" };
			TileMap[11] = { "llkkookkookkookkookkookkookkll" };
			TileMap[12] = { "llmmoommoommoommoommoommoommll" };
			TileMap[13] = { "lloooooooommoooooommooooooooll" };
			TileMap[14] = { "lluuuuooookkoouuookkoooouuuull" };
			TileMap[15] = { "lluuuuooookkoouuookkoooouuuull" };
			TileMap[16] = { "lluuuuuuuukkkkuukkkkuuuuuuuull" };
			TileMap[17] = { "lluuuuuuuukkoouuookkuuuuuuuull" };
			TileMap[18] = { "lluuuuuuuuuuuuuuuuuuuuuuuuuull" };
			TileMap[19] = { "lluuuuuuuuuuuuuuuuuuuuuuuuuull" };
			TileMap[20] = { "llooooooookkuuuuuukkooooooooll" };
			TileMap[21] = { "llkkookkookkuuuuuukkookkookkll" };
			TileMap[22] = { "llookkookkoooouuooookkookkooll" };
			TileMap[23] = { "llookkookkoooouuooookkookkooll" };
			TileMap[24] = { "llookkookkooooooooookkookkooll" };
			TileMap[25] = { "llookkookkoookkkkoookkookkooll" };
			TileMap[26] = { "llookkookkoookghkoookkookkooll" };
			TileMap[27] = { "lloooooooooookbnkoooooooooooll" };
		}
		if (i == 20) {
			TileMap[2] = { "lloooooovvookkooookkookkooooll" };
			TileMap[3] = { "lloooooovvookkooookkookkooooll" };
			TileMap[4] = { "llooooooooooooooookkoommooooll" };
			TileMap[5] = { "llooooooooooooooookkoommooooll" };
			TileMap[6] = { "lloooooovvoooommookkookkooooll" };
			TileMap[7] = { "lloooooovvookkmmookkookkooooll" };
			TileMap[8] = { "llmmookkvvoommooookkookkooooll" };
			TileMap[9] = { "llooookkvvoommookkooookkooooll" };
			TileMap[10] = { "llooookkvvooooookkooooooooooll" };
			TileMap[11] = { "llooookkvvooooookkooooooooooll" };
			TileMap[12] = { "llkkookkvvvvoovvvvvvvvooookkll" };
			TileMap[13] = { "llkkookkvvvvoovvvvvvvvooookkll" };
			TileMap[14] = { "lloooooooooooooouuoovvoommmmll" };
			TileMap[15] = { "llooooookkoooooouuoovvooooooll" };
			TileMap[16] = { "llkkkkokkkoommuuuuuuvvooooooll" };
			TileMap[17] = { "llkkkkokkkoommuuuuuuvvookkkkll" };
			TileMap[18] = { "llkkoookooookkuuuuuuvvookkooll" };
			TileMap[19] = { "lloooookooookkuuuuuuvvookkooll" };
			TileMap[20] = { "llooooooooookkoouuoovvoouuooll" };
			TileMap[21] = { "lloommooooookkoouuoovvoouuooll" };
			TileMap[22] = { "llookkooooookkkkkkoooouuuuuull" };
			TileMap[23] = { "llookkoommoooooooooooouuuuuull" };
			TileMap[24] = { "llookkookkoooooooooovvuuuuuull" };
			TileMap[25] = { "llookkookkoookkkkooovvuuuuuull" };
			TileMap[26] = { "lloooooooooookghkooovvoouuooll" };
			TileMap[27] = { "lloooooooooookbnkooovvoouuooll" };
		}
		if (i == 21) {
			TileMap[2] = { "llooooooooooooooooooooooooooll" };
			TileMap[3] = { "llooooookkkkkkooookkooooooooll" };
			TileMap[4] = { "llooookkkkkkkkkkkkkkkkooooooll" };
			TileMap[5] = { "llooookkkkkkkkkkkkkkkkooooooll" };
			TileMap[6] = { "lloouuuuuuuuuuuuuuuukkkkooooll" };
			TileMap[7] = { "lloouuuuuuuuuuuuuuuukkkkooooll" };
			TileMap[8] = { "lluuuuoooooooooooouuuukkkkooll" };
			TileMap[9] = { "lluuuuoooooooooooouuuukkkkooll" };
			TileMap[10] = { "lluuoommoooommoooooouuuuuuooll" };
			TileMap[11] = { "lluuoommoooommoooooouuuuuuooll" };
			TileMap[12] = { "lluuoommoooommoooooouuuuuuooll" };
			TileMap[13] = { "lluuoommoooommoooooouuuuuuooll" };
			TileMap[14] = { "lluuoooouuoooooooouuuukkkkkoll" };
			TileMap[15] = { "lluuoooouuoooooooouuuukkkkkoll" };
			TileMap[16] = { "lluuuuuuuuuuuuuuuuuukkkkkkkoll" };
			TileMap[17] = { "lluuuuuuuuuuuuuuuuuukkkkkkkoll" };
			TileMap[18] = { "llkkuuuukkkkuuuuuukkkkkkkkooll" };
			TileMap[19] = { "llkkuuuukkkkuuuuuukkkkkkkkooll" };
			TileMap[20] = { "llookkkkkkkkkkkkkkkkkkkkoommll" };
			TileMap[21] = { "llookkkkkkkkkkkkkkkkkkkkoommll" };
			TileMap[22] = { "llmmookkmmkkkkkkkkkkkkkooommll" };
			TileMap[23] = { "llmmookkmmkkkkkkkkkkkkkooommll" };
			TileMap[24] = { "lloommkkkkmmooooookkkkmmmmmmll" };
			TileMap[25] = { "lloommkkoommokkkkokkuummmmmmll" };
			TileMap[26] = { "lloooooooooookghkoooooooooooll" };
			TileMap[27] = { "lloooooooooookbnkoooooooooooll" };
		}
		if (i == 22) {
			TileMap[2] = { "lloooooooooouuooooooooooooooll" };
			TileMap[3] = { "lloooooooooouuooooooooooooooll" };
			TileMap[4] = { "lloooooooouummuuooooooooooooll" };
			TileMap[5] = { "lloooooooouummuuooooooooooooll" };
			TileMap[6] = { "lloooouuoooouuoooouuuuooooooll" };
			TileMap[7] = { "lloooouuoooouuoooouuuuooooooll" };
			TileMap[8] = { "lloouukkuuoooooouukkkkuuooooll" };
			TileMap[9] = { "lloouukkuuoooooouukkkkuuooooll" };
			TileMap[10] = { "lloooouukkuuoooooouuuuoooouull" };
			TileMap[11] = { "lloooouukkuuoooooouuuuoooouull" };
			TileMap[12] = { "lluuoooouuoooouuoooooooouummll" };
			TileMap[13] = { "lluuoooouuoooouuoooooooouummll" };
			TileMap[14] = { "llkkuuoooooouummuuoooouuoouull" };
			TileMap[15] = { "llkkuuoooooouummuuoooouuoouull" };
			TileMap[16] = { "llmmkkuuoooooouuoooouummuuooll" };
			TileMap[17] = { "llmmkkuuoooooouuoooouummuuooll" };
			TileMap[18] = { "llkkuuoooouuoooooouuoouuooooll" };
			TileMap[19] = { "llkkuuoooouuoooooouuoouuooooll" };
			TileMap[20] = { "lluuoooouukkuuoouukkuuooooooll" };
			TileMap[21] = { "lluuoooouukkuuoouukkuuooooooll" };
			TileMap[22] = { "lloooooouukkuuoooouuoooouuooll" };
			TileMap[23] = { "lloooooouukkuuoooouuoooouuooll" };
			TileMap[24] = { "lloouuoooouuoooooooooouummuull" };
			TileMap[25] = { "lloouuoooouuokkkkooooouummuull" };
			TileMap[26] = { "lluummuuoooookghkooouukkuuooll" };
			TileMap[27] = { "lluummuuoooookbnkooouukkuuooll" };
		}
		if (i == 23) {
			TileMap[2] = { "llooooooooooooooooooooooooooll" };
			TileMap[3] = { "llooooooooooooooooooooooooooll" };
			TileMap[4] = { "lloooooooooommmmooooooooooooll" };
			TileMap[5] = { "lloooooooooommmmooooooooooooll" };
			TileMap[6] = { "lloooooooooooommooooooooooooll" };
			TileMap[7] = { "lloooooooooooommooooooooooooll" };
			TileMap[8] = { "lloommmmuuuukkmmkkuuuummmmooll" };
			TileMap[9] = { "lloommmmuuuukkmmkkuuuummmmooll" };
			TileMap[10] = { "lloooooommuuuummuuuummooooooll" };
			TileMap[11] = { "lloooooommuuuummuuuummooooooll" };
			TileMap[12] = { "lluuoooooommuuuuuummoooooouull" };
			TileMap[13] = { "lluuoooooommuuuuuummoooooouull" };
			TileMap[14] = { "llmmuuoooooouuuuuuoooooouummll" };
			TileMap[15] = { "llmmuuoooooouuuuuuoooooouummll" };
			TileMap[16] = { "lluuoooooooommuummoooooooouull" };
			TileMap[17] = { "lluuoooooommoouuoommoooooouull" };
			TileMap[18] = { "lloooooooommoooooommooooooooll" };
			TileMap[19] = { "lloooooooommoommoommooooooooll" };
			TileMap[20] = { "lloooooommoooommoooommooooooll" };
			TileMap[21] = { "lloooooommoooommoooommooooooll" };
			TileMap[22] = { "llooooooooooooooooooooooooooll" };
			TileMap[23] = { "llooooooooooooooooooooooooooll" };
			TileMap[24] = { "llooooooooooooooooooooooooooll" };
			TileMap[25] = { "lloooooooooookkkkoooooooooooll" };
			TileMap[26] = { "lloooommoooookghkooooommooooll" };
			TileMap[27] = { "lloooommoooookbnkooooommooooll" };
		}
		if (i == 24) {
			TileMap[2] = { "lloooommookkmmoooooooookooooll" };
			TileMap[3] = { "lloooommookkoooooooooookooooll" };
			TileMap[4] = { "llooookkookkuuookkkkkkkkooooll" };
			TileMap[5] = { "llooookkookkuuooookkkkkkooooll" };
			TileMap[6] = { "lloouuuuookkuuokkooooooommmmll" };
			TileMap[7] = { "lloouuuuookkuuokkooooooommmmll" };
			TileMap[8] = { "lluuuuuuuuuuuukkkkkkoookkkooll" };
			TileMap[9] = { "lluuuuuuuuuuuukkkkkkoookkkooll" };
			TileMap[10] = { "lloooouuuuoooommkkoookkkkkokll" };
			TileMap[11] = { "lloooouuuukkkkookkoookkkoookll" };
			TileMap[12] = { "llkkmmooookkkkooooookkkkoookll" };
			TileMap[13] = { "llkkooookkooooooooookkoooookll" };
			TileMap[14] = { "llokooookkjjjjjjjjjjjjjjjjjjll" };
			TileMap[15] = { "llokookkkkjjjjjjjjjjjjjjjjjjll" };
			TileMap[16] = { "llokookkoojjjjjjjjjjjjjjjjjjll" };
			TileMap[17] = { "llokoooooojjjjjjjjjjjjjjjjjjll" };
			TileMap[18] = { "lloooommoojjjjjjjjjjjjjjjjjjll" };
			TileMap[19] = { "lloooommoojjjjjjjjjjjjjjjjjjll" };
			TileMap[20] = { "llkkookkoojjjjjjjjjjjjjjjjjjll" };
			TileMap[21] = { "llkkookkoojjjjjjjjjjjjjjjjjjll" };
			TileMap[22] = { "llokookkoojjjjjjjjjjjjjjjjjjll" };
			TileMap[23] = { "llokookkoojjjjjjjjjjjjjjjjjjll" };
			TileMap[24] = { "llokookkoooooooooojjjjjjjjjjll" };
			TileMap[25] = { "llokookkoooookkkkojjjjjjjjjjll" };
			TileMap[26] = { "llooookkoooookghkooojjjjjjjjll" };
			TileMap[27] = { "lloooooooooookbnkooojjjjjjjjll" };
		}
		if (i == 25) {
			TileMap[2] = { "lloooooommookkookkookkoommooll" };
			TileMap[3] = { "lloooooommookkookkookkoommooll" };
			TileMap[4] = { "llookkookkoooooooooommooooooll" };
			TileMap[5] = { "llookkookkoooooooooommooooooll" };
			TileMap[6] = { "llookkookkoooommoooommoommmmll" };
			TileMap[7] = { "llookkookkoooommoooommoommmmll" };
			TileMap[8] = { "llookkooooookkoommkkoooooommll" };
			TileMap[9] = { "llookkooooookkoommkkoooooommll" };
			TileMap[10] = { "llooooooookkkkookkkkoommooooll" };
			TileMap[11] = { "llooooooookkkkookkkkoommooooll" };
			TileMap[12] = { "lloooommookkooookkkkookkkkooll" };
			TileMap[13] = { "lloooommookkooookkkkookkkkooll" };
			TileMap[14] = { "llmmoommooookkoommoooommkkooll" };
			TileMap[15] = { "llmmoommooookkoommoooommkkooll" };
			TileMap[16] = { "llooookkkkookkooooookkmmooooll" };
			TileMap[17] = { "llooookkkkookkooooookkmmooooll" };
			TileMap[18] = { "lloommkkkkookkkkookkkkooookkll" };
			TileMap[19] = { "lloommkkkkookkkkookkkkooookkll" };
			TileMap[20] = { "llookkooooookkmmooooooookkkkll" };
			TileMap[21] = { "llookkooooookkmmooooooookkkkll" };
			TileMap[22] = { "llooooookkookkkkmmoommooookkll" };
			TileMap[23] = { "llooooookkookkkkmmoommooookkll" };
			TileMap[24] = { "llkkookkkkooooooooookkmmooooll" };
			TileMap[25] = { "llkkookkkkoookkkkoookkmmooooll" };
			TileMap[26] = { "llkkookkoooookghkoookkkkkkooll" };
			TileMap[27] = { "llkkookkoooookbnkoookkkkkkooll" };
		}
		if (i == 26) {
			TileMap[2] = { "lloooovvvvooooooooooooooooooll" };
			TileMap[3] = { "lloooovvvvooooooooooooooooooll" };
			TileMap[4] = { "lloooooovvuuookoooooooooooooll" };
			TileMap[5] = { "llmmoooovvuuookoooooooooooooll" };
			TileMap[6] = { "lluuoooooooooomoookooovvvvooll" };
			TileMap[7] = { "lluummoooooooomoookooovvvvooll" };
			TileMap[8] = { "lluuuuoommoookoooomouuvvooooll" };
			TileMap[9] = { "lluuuuooookkokoooomouuvvooooll" };
			TileMap[10] = { "lluuuuuuoooommoookooooooooooll" };
			TileMap[11] = { "lluuuuuuoooommkkokoooooooommll" };
			TileMap[12] = { "lluuuummoooookoommoooooooouull" };
			TileMap[13] = { "lluuuuoommoookoommkkoooommuull" };
			TileMap[14] = { "lluummooookkmmoookoommoouuuull" };
			TileMap[15] = { "lluuoooooooommoookoooooouuuull" };
			TileMap[16] = { "llooooooooookokkmmoooouuuuuull" };
			TileMap[17] = { "llooooooooookooommoooouuuuuull" };
			TileMap[18] = { "lloooovvuuomooookokkoommuuuull" };
			TileMap[19] = { "lloooovvuuomooookooommoouuuull" };
			TileMap[20] = { "lloovvvvoookooomoooooooooouull" };
			TileMap[21] = { "lloovvvvoookooomoooooooooouull" };
			TileMap[22] = { "lloooooooooooookoouuvvoooommll" };
			TileMap[23] = { "lloooooooooooookoouuvvooooooll" };
			TileMap[24] = { "llmmoooooooooooooooovvvvooooll" };
			TileMap[25] = { "llmmoooooooookkkkooovvvvooooll" };
			TileMap[26] = { "llmmoooooooookghkooooooooommll" };
			TileMap[27] = { "llmmoooooooookbnkooooooooommll" };
		}
		if (i == 27) {
			TileMap[2] = { "lloooooooommooooooooooooooooll" };
			TileMap[3] = { "lloooooooommooooooooooooooooll" };
			TileMap[4] = { "llmmmmoooommoooommmmooooooooll" };
			TileMap[5] = { "llmmmmoooommoooommmmooooooooll" };
			TileMap[6] = { "lloommoooommoooooommoommmmuull" };
			TileMap[7] = { "lloommoooommoooooommoommmmuull" };
			TileMap[8] = { "lloommoooommmmmmoouuoommooooll" };
			TileMap[9] = { "lloommoooommmmmmoouuoommooooll" };
			TileMap[10] = { "llookkoooooooommoommmmmmooooll" };
			TileMap[11] = { "llookkoooooooommoommmmmmooooll" };
			TileMap[12] = { "lluummmmoommkkmmkkkkooooooooll" };
			TileMap[13] = { "lluummmmoommkkmmkkkkooooooooll" };
			TileMap[14] = { "lloooommuummuuooookkoooommmmll" };
			TileMap[15] = { "lloooommuummuuooookkoooommmmll" };
			TileMap[16] = { "lloooommoooouuoooommoooommooll" };
			TileMap[17] = { "lloooommoooouuoooommoooommooll" };
			TileMap[18] = { "llooookkoooommoooommmmkkmmooll" };
			TileMap[19] = { "llooookkoooommoooommmmkkmmooll" };
			TileMap[20] = { "lluummmmmmuuuukkmmmmookkmmooll" };
			TileMap[21] = { "lluummmmmmuuuukkmmmmookkmmooll" };
			TileMap[22] = { "llooooookkoooooooouuuuookkooll" };
			TileMap[23] = { "llooooookkoooooooouuuuookkooll" };
			TileMap[24] = { "lloooooommoooooooooouuookkooll" };
			TileMap[25] = { "lloooooommoookkkkooouuookkooll" };
			TileMap[26] = { "lloooooommoookghkooommookkooll" };
			TileMap[27] = { "lloooooommoookbnkooommookkooll" };
		}
		if (i == 28) {
			TileMap[2] = { "llooooooooooooooooooooommoooll" };
			TileMap[3] = { "llooooooooooooooooooooommoooll" };
			TileMap[4] = { "lloooooooooooooooooooommooooll" };
			TileMap[5] = { "lloooooooooooommoooooommooooll" };
			TileMap[6] = { "lloooooooooooouuooookkkoooooll" };
			TileMap[7] = { "llooooooooookkuukkookkkoooooll" };
			TileMap[8] = { "lloooooooooouuuuuuookkkoooooll" };
			TileMap[9] = { "lloooooooommuuuuuummkkkoooooll" };
			TileMap[10] = { "lloooooooouuuujjuuuukkkoooooll" };
			TileMap[11] = { "llooooookkuuuujjuuuukkkoooooll" };
			TileMap[12] = { "lloooooouuuujjjjjjuuuukoooooll" };
			TileMap[13] = { "lloooommuuuujjjjjjuuuukoooooll" };
			TileMap[14] = { "lloooouuuujjjjjjjjjjuuuuooooll" };
			TileMap[15] = { "llookkuuuujjjjjjjjjjuuuukkooll" };
			TileMap[16] = { "lloouuuujjjjjjjjjjjjjjuuuuooll" };
			TileMap[17] = { "llmmuuuujjjjjjjjjjjjjjuuuummll" };
			TileMap[18] = { "llkkuujjjjjjjjjjjjjjjjjjuuuull" };
			TileMap[19] = { "llkkuujjjjjjjjjjjjjjjjjjuuuull" };
			TileMap[20] = { "lloouujjjjjjjjjjjjjjjjjjuuooll" };
			TileMap[21] = { "lloouujjjjjjjjjjjjjjjjjjuuooll" };
			TileMap[22] = { "lloouujjjjjjjjjjjjjjjjjjuuooll" };
			TileMap[23] = { "lloouujjjjjjjjjjjjjjjjjjuuooll" };
			TileMap[24] = { "lloouujjjjjjoooooojjjjjjuuooll" };
			TileMap[25] = { "lloouujjjjjjokkkkojjjjjjuuooll" };
			TileMap[26] = { "lloooooooooookghkooojjjjjjjjll" };
			TileMap[27] = { "lloooooooooookbnkooojjjjjjjjll" };
		}
		if (i == 29) {
			TileMap[2] = { "llooooooooooooooooooookkooooll" };
			TileMap[3] = { "llooooooooooooooooooookkooooll" };
			TileMap[4] = { "llookkvvvvoommookkooooooooooll" };
			TileMap[5] = { "llookkvvvvoommookkooooooooooll" };
			TileMap[6] = { "lloooovvvvkkuuuuuuvvvvoommooll" };
			TileMap[7] = { "lloooovvvvkkuuuuuuvvvvoommooll" };
			TileMap[8] = { "lloooooooouuuuoouuooooooooooll" };
			TileMap[9] = { "lloooooooouuuuoouuooooooooooll" };
			TileMap[10] = { "lloommoooovvvvoouuooooooooooll" };
			TileMap[11] = { "lloommoooovvvvoouuooooooooooll" };
			TileMap[12] = { "lluuuukkoovvvvmmooooooookkooll" };
			TileMap[13] = { "lluuuukkoovvvvmmooooooookkooll" };
			TileMap[14] = { "lluuuuuuoooooooooooommoooommll" };
			TileMap[15] = { "lluuuuuuoooooooooooommoooommll" };
			TileMap[16] = { "llookkvvvvookkooooooooooooooll" };
			TileMap[17] = { "llookkvvvvookkooooooooooooooll" };
			TileMap[18] = { "llmmoovvvvuuuuvvvvuuuuookkooll" };
			TileMap[19] = { "llmmoovvvvuuuuvvvvuuuuookkooll" };
			TileMap[20] = { "lloooooooouuoovvvvuuuuvvvvooll" };
			TileMap[21] = { "lloooooooouuoovvvvuuuuvvvvooll" };
			TileMap[22] = { "lloooooommuuoooooouuuuvvvvooll" };
			TileMap[23] = { "lloooooommuuoooooouuuuvvvvooll" };
			TileMap[24] = { "llooookkookkooooooooooooooooll" };
			TileMap[25] = { "llooookkookkokkkkoooooooooooll" };
			TileMap[26] = { "llkkoooooooookghkoookkmmooooll" };
			TileMap[27] = { "llkkoooooooookbnkoookkmmooooll" };
		}
		if (i == 30) {
			TileMap[2] = { "llooooooooooooooooooooooooooll" };
			TileMap[3] = { "llooooooooooooooooooooooooooll" };
			TileMap[4] = { "llooooooooooooooooooooooooooll" };
			TileMap[5] = { "llooooooooookkkkooooookkooooll" };
			TileMap[6] = { "lloooooooooouuuuoooooouuooooll" };
			TileMap[7] = { "lloommmmookkuuuummookkuukkooll" };
			TileMap[8] = { "lloouuuuoouuuuuuuuoouuuuuuooll" };
			TileMap[9] = { "llkkuuuukkuuuuuuuukkuuuuuukkll" };
			TileMap[10] = { "lluuuuuuuuuuuuuuuuuuuuuuuuuull" };
			TileMap[11] = { "lluuuuuuuuuuuuuuuuuuuuuuuuuull" };
			TileMap[12] = { "llmmuuvvuuuuuuuuuuvvuuuuuuuull" };
			TileMap[13] = { "llmmuuvvuuuuuuuuuuvvuuuuuuuull" };
			TileMap[14] = { "lluuuuvvvvvvuuuuuuvvvvvvuummll" };
			TileMap[15] = { "lluuuuvvvvvvuuuuuuvvvvvvuummll" };
			TileMap[16] = { "lluuuuuuuuvvuummuuuuuuvvuuuull" };
			TileMap[17] = { "lluuuuuuuuvvuummuuuuuuvvuuuull" };
			TileMap[18] = { "lluuuuuuuuuuuuuuuuuuuuuuuuuull" };
			TileMap[19] = { "lluuuuuuuuuuuuuuuuuuuuuuuuuull" };
			TileMap[20] = { "lluuuuuuuuuukkkkuuuuuuuuuummll" };
			TileMap[21] = { "lluuuuuuuuuuoooouuuuuuuuuuooll" };
			TileMap[22] = { "llmmuuuuuukkooookkuuuuuummooll" };
			TileMap[23] = { "lloouuuuuuoooooooouuuuuuooooll" };
			TileMap[24] = { "lloommkkkkooooooookkkkkkooooll" };
			TileMap[25] = { "lloooooooooookkkkoooooooooooll" };
			TileMap[26] = { "lloooooooooookghkoooooooooooll" };
			TileMap[27] = { "lloooooooooookbnkoooooooooooll" };
		}
		if (i == 31) {
			TileMap[2] = { "lloooooovvoooooooovvooooooooll" };
			TileMap[3] = { "lloooooovvoooooooovvooooooooll" };
			TileMap[4] = { "llvvvvoovvoovvvvvvvvoovvvvvvll" };
			TileMap[5] = { "llvvvvoovvoovvvvvvvvoovvvvvvll" };
			TileMap[6] = { "lluuuukkooookkoooovvoovvuuvvll" };
			TileMap[7] = { "lluuuukkooookkoooovvoovvuuvvll" };
			TileMap[8] = { "lluuvvvvvvvvoommooookkuuuuuull" };
			TileMap[9] = { "lluuvvvvvvvvoommooookkuuuuuull" };
			TileMap[10] = { "lluuuuoovvoooovvoovvvvvvvvuull" };
			TileMap[11] = { "lluuuuoovvoooovvoovvvvvvvvuull" };
			TileMap[12] = { "llvvvvoovvoovvvvoooovvooooooll" };
			TileMap[13] = { "llvvvvoovvoovvvvoooovvooooooll" };
			TileMap[14] = { "llooookkuukkookkuuoovvoooovvll" };
			TileMap[15] = { "llooookkuukkookkuuoovvoooovvll" };
			TileMap[16] = { "lloovvvvuuvvvvvvvvoouukkoovvll" };
			TileMap[17] = { "lloovvvvuuvvvvvvvvoouukkoovvll" };
			TileMap[18] = { "llkkooookkoooovvoouuuuvvoovvll" };
			TileMap[19] = { "llkkooookkoooovvoouuuuvvoovvll" };
			TileMap[20] = { "llvvvvoovvvvoovvkkvvvvvvooooll" };
			TileMap[21] = { "llvvvvoovvvvoovvkkvvvvvvooooll" };
			TileMap[22] = { "llooookkoouuuuoooouuvvoooovvll" };
			TileMap[23] = { "llooookkoouuuuoooouuvvoooovvll" };
			TileMap[24] = { "lloovvvvvvuuoooooooovvoovvvvll" };
			TileMap[25] = { "lloovvvvvvuuokkkkooovvoovvvvll" };
			TileMap[26] = { "lloovvoooooookghkoooooooooooll" };
			TileMap[27] = { "lloovvoooooookbnkoooooooooooll" };
		}
		if (i == 32) {
			TileMap[2] = { "lljjjjjjjjjjjjjjjjjjjjjjjjjjll" };
			TileMap[3] = { "lljjjjjjjjjjjjjjjjjjjjjjjjjjll" };
			TileMap[4] = { "lljjjjjjjjjjjjjjjjjjjjjjjjjjll" };
			TileMap[5] = { "lljjjjjjjjjjjjjjjjjjjjjjjjjjll" };
			TileMap[6] = { "lljjjjjjkkjjjjjjjjjjkkjjjjjjll" };
			TileMap[7] = { "lljjjjjjkkjjjjjjjjjjkkjjjjjjll" };
			TileMap[8] = { "lljjkkookkookkjjkkookkookkjjll" };
			TileMap[9] = { "lljjkkookkookkjjkkookkookkjjll" };
			TileMap[10] = { "lljjkkkkkkooooooooookkkkkkjjll" };
			TileMap[11] = { "lljjooookkooooooooookkoooojjll" };
			TileMap[12] = { "lljjjjjjkkookkmmkkookkjjjjjjll" };
			TileMap[13] = { "lljjjjjjkkkkkkmmkkkkkkjjjjjjll" };
			TileMap[14] = { "llmmjjjjjjoommoommoojjjjjjmmll" };
			TileMap[15] = { "llmmjjjjjjoooooooooojjjjjjmmll" };
			TileMap[16] = { "lljjjjjjjjoooooooooojjjjjjjjll" };
			TileMap[17] = { "lljjjjjjjjookkookkoojjjjjjjjll" };
			TileMap[18] = { "lljjjjjjjjookkookkoojjjjjjjjll" };
			TileMap[19] = { "lljjjjjjjjookkookkoojjjjjjjjll" };
			TileMap[20] = { "lljjjjjjkkooooooooookkjjjjjjll" };
			TileMap[21] = { "lljjjjjjkkooookkooookkjjjjjjll" };
			TileMap[22] = { "lljjkkjjkkoommmmmmookkjjkkjjll" };
			TileMap[23] = { "lljjkkjjkkooooooooookkjjkkjjll" };
			TileMap[24] = { "llookkookkooooooooookkookkooll" };
			TileMap[25] = { "llookkkkkkoookkkkoookkkkkkooll" };
			TileMap[26] = { "llookkoooooookghkoooooookkooll" };
			TileMap[27] = { "lloooooooooookbnkoooooooooooll" };
		}
		if (i == 33) {
			TileMap[2] = { "lloooooooommoooooooommooooooll" };
			TileMap[3] = { "lloooooooommoooooooommooooooll" };
			TileMap[4] = { "lloommoooooommoooommuuuuooooll" };
			TileMap[5] = { "lloommoooooommoooommuuuuooooll" };
			TileMap[6] = { "lloooommoooooooommkkoomoooooll" };
			TileMap[7] = { "lloooommoooooooommkkmmmoooooll" };
			TileMap[8] = { "lloooooommoouuuuuuuuuuooomooll" };
			TileMap[9] = { "lloooooommoouuuuuuuuuuooomooll" };
			TileMap[10] = { "lloomooooommuuuummuuoooommooll" };
			TileMap[11] = { "lloomooooommuuuummuuoooommooll" };
			TileMap[12] = { "lloommmouuoommuuuummooooomooll" };
			TileMap[13] = { "lloooomouuoommuuuummooooomooll" };
			TileMap[14] = { "lloooouuuuuuuuuuoooommooooooll" };
			TileMap[15] = { "lloooouuuuuuuuuuoooommooooooll" };
			TileMap[16] = { "lloooomouuoommuuoooooommooooll" };
			TileMap[17] = { "lloommmouuoommuuoooooommooooll" };
			TileMap[18] = { "lloouuuuuummoommoooooooommooll" };
			TileMap[19] = { "lloouuuuuummoommoommoooommooll" };
			TileMap[20] = { "lluuuuuummooooooooomooooooooll" };
			TileMap[21] = { "lluuuuuummooooooooomooooooooll" };
			TileMap[22] = { "lloooommooooooooooooooooommmll" };
			TileMap[23] = { "lloooommooooooooooooooooommmll" };
			TileMap[24] = { "lloooooooooooooooooooomoooooll" };
			TileMap[25] = { "lloooooooooookkkkooommmoooooll" };
			TileMap[26] = { "llmooooooooookghkoooooooooooll" };
			TileMap[27] = { "llmooommoooookbnkoooooooooooll" };
		}
		if (i == 34) {
			TileMap[2] = { "llooooooookookookoooooooooooll" };
			TileMap[3] = { "llooooooookookookoooooooooooll" };
			TileMap[4] = { "llkokokookookooooookokooooooll" };
			TileMap[5] = { "llkokokookookooooookokooooooll" };
			TileMap[6] = { "llkokokokkkkoooooookokkkooooll" };
			TileMap[7] = { "llkokokokkkkoooooookokkkooooll" };
			TileMap[8] = { "llokokookkkoooooookkokkkkoooll" };
			TileMap[9] = { "llokokookkkoooooookkokkkkoooll" };
			TileMap[10] = { "llookoookkokkoookokkkkkkooooll" };
			TileMap[11] = { "llookoookkokkoookokkkkkkooooll" };
			TileMap[12] = { "llookookooookkkokkokokkkooooll" };
			TileMap[13] = { "llookookooookkkokkokokkkooooll" };
			TileMap[14] = { "llookooooookkkkkkoookokkooooll" };
			TileMap[15] = { "llookooooookkkkkkoookokkooooll" };
			TileMap[16] = { "lloookooookokkkkkoookokkooooll" };
			TileMap[17] = { "lloookooookokkkkkoookokkooooll" };
			TileMap[18] = { "lloookkkkkookkkkkkookokokkkkll" };
			TileMap[19] = { "lloookkkkkookkkkkkookokokkkkll" };
			TileMap[20] = { "lloookoooookokokkokkokokoookll" };
			TileMap[21] = { "lloookoooookokokkokkokokoookll" };
			TileMap[22] = { "llooookookkokkokkkkoooookoooll" };
			TileMap[23] = { "llooookookkokkokkkkoooookoooll" };
			TileMap[24] = { "llooookookkooooooookkkoookooll" };
			TileMap[25] = { "llooookookkookkkkokkkoookoooll" };
			TileMap[26] = { "llooookookoookghkoookkkkooooll" };
			TileMap[27] = { "llooookookoookbnkoookkkkooooll" };
		}
		if (i == 35) {
			TileMap[2] = { "llooooooooooooooooooooooooooll" };
			TileMap[3] = { "llooooooooooooooooooooooooooll" };
			TileMap[4] = { "llooooooookkookkooooooooooooll" };
			TileMap[5] = { "llooooooookkookkooooooooooooll" };
			TileMap[6] = { "lluuoooouukkuukkuuoooouuooooll" };
			TileMap[7] = { "lluuoooouukkuukkuuoooouuooooll" };
			TileMap[8] = { "llkkuuuukkkkkkkkkkuuuukkuuooll" };
			TileMap[9] = { "llkkuuuukkkkkkkkkkuuuukkuuooll" };
			TileMap[10] = { "llkkkkkkkkmmkkmmkkkkkkkkuuooll" };
			TileMap[11] = { "llkkkkkkkkmmkkmmkkkkkkkkuuooll" };
			TileMap[12] = { "llvvvvvvkkkkkkkkkkvvvvvvuuooll" };
			TileMap[13] = { "llvvvvvvkkkkkkkkkkvvvvvvuuooll" };
			TileMap[14] = { "llvvkkkkkkkkkkkkkkkkkkvvvvuull" };
			TileMap[15] = { "llvvkkkkkkkkkkkkkkkkkkvvvvuull" };
			TileMap[16] = { "llkkkkkkvvkkkkkkvvkkkkkkuuuull" };
			TileMap[17] = { "llkkkkkkvvkkkkkkvvkkkkkkuuuull" };
			TileMap[18] = { "llkkkkvvvvvvkkvvvvvvkkkkvvvvll" };
			TileMap[19] = { "llkkkkvvvvvvkkvvvvvvkkkkvvvvll" };
			TileMap[20] = { "lluuvvvvuuuuuuuuuuvvvvuuvvuull" };
			TileMap[21] = { "lluuvvvvuuuuuuuuuuvvvvuuvvuull" };
			TileMap[22] = { "lloouuuuoooooooooouuuuoouuooll" };
			TileMap[23] = { "lloouuuuoooooooooouuuuoouuooll" };
			TileMap[24] = { "llooooooooooooooooooooooooooll" };
			TileMap[25] = { "lloooooooooookkkkoooooooooooll" };
			TileMap[26] = { "lloooooooooookghkoooooooooooll" };
			TileMap[27] = { "lloooooooooookbnkoooooooooooll" };
		}
	}


